Silently remove existing dkms modules in postinst Don't abort if removing dkms modules fails in prerm

diff --git a/debian/virtualbox-ose-guest-source.postinst b/debian/virtualbox-ose-guest-source.postinst
--- a/debian/virtualbox-ose-guest-source.postinst
+++ b/debian/virtualbox-ose-guest-source.postinst
@@ -18,6 +18,8 @@ case "$1" in
 			fi
 		fi
 
+		#Silently remove existing modules
+		dkms remove -m virtualbox-ose-guest -v $CVERSION --all > /dev/null 2>&1 || true
 		#Create DKMS modules
 		echo "Adding Module to DKMS build system"
 		dkms add -m virtualbox-ose-guest -v $CVERSION > /dev/null
diff --git a/debian/virtualbox-ose-source.postinst b/debian/virtualbox-ose-source.postinst
--- a/debian/virtualbox-ose-source.postinst
+++ b/debian/virtualbox-ose-source.postinst
@@ -18,6 +18,10 @@ case "$1" in
 			fi
 		fi
 
+		#Silently remove existing modules
+		dkms remove -m vboxdrv -v $CVERSION --all > /dev/null 2>&1 || true
+		dkms remove -m vboxnetflt -v $CVERSION --all > /dev/null 2>&1 || true
+		dkms remove -m vboxnetadp -v $CVERSION --all > /dev/null 2>&1 || true
 		#Create DKMS modules
 		echo "Adding modules to DKMS build system"
 		dkms add -m vboxdrv -v $CVERSION > /dev/null
